POWERCARD_POST_TYPE_ID = 1
CAREERS_POST_TYPE_ID = 2
EXPERIENCE_POST_TYPE_ID = 3
TERM_CONDITION_POST_TYPE_ID = 4
HELIO_ABOUT_POST_TYPE_ID = 5
NEWS_POST_TYPE_ID = 6
HELIO_PHOTOS_POST_TYPE_ID = 7
ORTHER_PROD_POST_TYPE_ID = 8

POWERCARD_CATEGORY=1
HELIO_PLAY_CATEGORY=2
HELIO_KIDS_CATEGORY=3
NIGHT_LIFE_CATEGORY=4
REDEMPTION_STORE_CATEGORY=5
OTHER_PRODUCT_CATEGORY=6
COFFEE_CATEGORY=7

NIGHT_LIFE_KEY_QUERY='kq_night_life'
COFFEE_KEY_QUERY='kq_coffee'
REDEMPTION_STORE_KEY_QUERY='kq_redemption_store'
POLICY_KEY_QUERY="kq_policy"
KIDS_PRICING_KEY_QUERY='kq_kids_pricing'
TIME_ACTIVE_KEY_QUERY='kq_time_active'
TERM_AND_CONDITION_KEY_QUERY='kq_term_and_condition'