# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'avatar'),
        ),
    ]
