# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_device_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion_label',
            name='promotion',
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_label_rel', to='core.Promotion_Label'),
        ),
    ]
