# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170518_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='promotion_label',
            options={'verbose_name': 'Promotion Label', 'verbose_name_plural': 'Promotion Label'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_type',
        ),
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_category_rel', to='core.Category'),
        ),
        migrations.DeleteModel(
            name='Entertainment',
        ),
    ]
