# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170615_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_notification',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category_notification',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject_vi',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
