# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170615_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_category_rel', to='core.Category_Notification'),
        ),
    ]
