# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170615_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='description_game',
            new_name='description_detail',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='description_game_en',
            new_name='description_detail_en',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='description_game_vi',
            new_name='description_detail_vi',
        ),
    ]
