# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170615_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(choices=[(b'android', b'Android'), (b'ios', b'IOS')], default=b'ios', max_length=255),
        ),
    ]
