# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, choices=[(b'android', b'Android'), (b'ios', b'IOS')], max_length=255, null=True),
        ),
    ]
