# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170616_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_register',
            field=models.BooleanField(default=True),
        ),
    ]
