# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_is_new_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=b''),
        ),
    ]
