# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_uid',
        ),
        migrations.AddField(
            model_name='user',
            name='flag_notification',
            field=models.BooleanField(default=True),
        ),
    ]
