# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170622_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
